name: Questions + general issues
description: In need of help or don't have a specific bug or feature? Use this!
title: "[issue name]"
labels: ['question']
assignees:
  - iron-fish/engineering
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: What do you need help with?
      placeholder: My issue is...
    validations:
      required: true
